name: CI workflow lib

on:
  release:
    types: [published]
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    uses: storytel/actions-toolkit/.github/workflows/golang-libs.yaml@SRE-329/golang-lib-support
    secrets: inherit
